Support installing to multiple ESPs
grub-multi-install runs grub-install over all (configured)
ESPs. The logic for configuration is copied from grub-pc,
including handling ESPs that have become absent.

On upgrade, we import the existing mounted /boot/efi into
our debconf setting, so as to avoid asking everyone this
question when they upgrade an existing installation.

On install, we want to do the same thing, to keep existing
installers working. However, we only do that if the option
is not yet set, thus allowing preseeding of the option, so
installers can configure multiple ESPs.

The ESP detection is copied from os-prober, with
ID_PART_ENTRY_SCHEME = msdos changed to dos, as that's
what udevadm info returns; os-prober has a wrapper around
udevadm info called udevinfo that probably changes that
to msdos to support older versions or whatever.

Avoid grub-mkdevicemap here, we do not need to (or can)
group the partitions by disk.

Set _UBUNTU_ALTERNATIVE_ESPS, the grub-installer will be
modified to read that variable and handle other ESPs it
is not currently working on.

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -297,6 +297,22 @@ get_mountpoint()
   echo "${boot_mountpoint:-/}"
 }
 
+# Parse /proc/mounts and find out the mount for the given device.
+# The device must be a real device in /dev, not a symlink to one.
+get_mounted_device()
+{
+  mountpoint="$1"
+  cat /proc/mounts | while read -r line; do
+    set -f
+    set -- $line
+    set +f
+    if [ "$2" = "$mountpoint" ]; then
+      echo "$1"
+      break
+    fi
+  done
+}
+
 config_item()
 {
   for x in /etc/default/grub /etc/default/grub.d/*.cfg; do
@@ -326,6 +342,14 @@ no_nvram_arg() {
 run_grub_install()
 {
     if ! grub-install $@ ; then
+        echo "Failed: grub-install $@" >&2
+        echo "WARNING: Bootloader is not properly installed, system may not be bootable" >&2
+    fi
+}
+
+run_grub_multi_install()
+{
+    if ! /usr/lib/grub/grub-multi-install $@ ; then
         echo "Failed: grub-install $@" >&2
         echo "WARNING: Bootloader is not properly installed, system may not be bootable" >&2
     fi
@@ -704,6 +728,20 @@ case "$1" in
           fi
         fi
 
+        # Backwards /boot/efi compatibility: Move /boot/efi into the debconf
+        # setting on upgrades and install.
+        db_get grub2/efi_install_devices || true
+        if [ -z "$RET" ] && dpkg --compare-versions "$2" lt 2.04-1ubuntu23~; then
+          esp="$(get_mounted_device /boot/efi)"
+          if [ "$esp" ]; then
+            esp="$(device_to_id "$esp")"
+          fi
+          if [ "$esp" ]; then
+            db_set grub2/efi_install_devices "$esp"
+            db_fset grub2/efi_install_devices seen true
+          fi
+        fi
+
         case @PACKAGE@ in
           grub-efi-ia32)  target=i386-efi ;;
           grub-efi-amd64) target=x86_64-efi ;;
@@ -717,7 +755,7 @@ case "$1" in
             NO_EXTRA_REMOVABLE="--no-extra-removable"
           fi
           NO_NVRAM="$(no_nvram_arg)"
-          run_grub_install --target="$target" "$NO_EXTRA_REMOVABLE" "$NO_NVRAM"
+          run_grub_multi_install --target="$target" "$NO_EXTRA_REMOVABLE" "$NO_NVRAM"
         fi
 
         # /boot/grub/ has more chances of being accessible by GRUB
